name: "validate-author"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      with:
        script: |
          const validateAuthor = require(
            `${process.env.GITHUB_WORKSPACE}/.github/actions/validate-author/index.js`
          );
          await validateAuthor({ context, github, core });
